language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
- pypy3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gherman
  password:
    secure: Vm7pzvlspsv28xEiU6F6LpcK5D7rcSuAsLvRtxXZni7/UaqRh4v8xo8mVOFVOBvgmUvXbBVJuhrIqu8l9bblrKKWv/JyaDqTIneDjF9L7bmnS7NTr72imLomIicyPZvZIdlOInO0eiJJy+2ZylJIW8gh4ZpQ4s7RJx2svPLkjgiNwR1dMHoE8Hy22GoxlsO8gGikwj71h+Bn1OyKB2qyEPm0Xa6N9tGti8GgvKrlunXltSPy7fpd0nwgZcH9ujY1rHCcWGLSiDi+nYoFq8TbemEJz0235rZemVIsXGrdskm6sAMZB4lv83YrStk9sLDrhyP4aoLd2/QR63elA/br1CBtxR+IvPWeERtdO1P42XT+g+Rf64Jw/1XJox8XPL2eGXO/pO56rRNtJTQsCPEQzdiGtMsOuXyJ5ygwlMcXpQeq1VCYadOjWyjO6Xtv85YofONHOsJC30RiJW6SvdBC9uKVPOWM5Ql6YKm7Pgr8FlUXGKi8XlEXonFkE/n18HS45qn6oIwiMT50Du+PLP9sBsYMhogcPKLkGgUQMV2T3YtNjHKN285my5k13eTB4zczeuHXdulqKxbCNq3qCM8xMzIDv05gTLGuvAYyRhyC2uQ+iMqn6SacspwShexZ/WvefQ4zcUNhsZPEG5aRmaVtKC77J5zFFCmbX14UfRxgGP0=
  on:
    tags: true
    repo: deeplook/asciinemaster
    python: 3.6
